Repository sivakumarreddy07/hokie-for-u, pull requests merged in 2023-11, with the labels that each got.

#6 Added backend code for post job functionality
  .gitignore
  client/src/index.js
  server/controllers/jobController.js
  server/controllers/userController.js
  server/models/job.js
  server/models/user.js
  server/package-lock.json
  server/package.json
  server/routes/jobRoutes.js
  server/server.js
Labels: User story

#7 config changes for mongodb connection string
  server/.gitignore
  server/config/default.json
  server/server.js
Labels: Task

#8 Added code for connecting frontend with backend for post a job functionality
  client/src/api/index.js
  client/src/components/PostJobApp.js
  client/src/css/PostJobApp.css
  client/src/redux/actions/auth.js
Labels: User story, Task

#9 Added backend functionalities
  server/controllers/jobController.js
  server/models/job.js
  server/models/user.js
  server/routes/jobRoutes.js
Labels: User story

#10 Added code for Update Profile functionality
  client/src/App.js
  client/src/api/index.js
  client/src/components/HeaderApp.js
  client/src/components/ProfileApp.js
  client/src/css/HeaderApp.css
  client/src/css/ProfileApp.css
  client/src/redux/actions/auth.js
  server/.gitignore
  server/controllers/userController.js
  server/package-lock.json
  server/package.json
  server/routes/userRoutes.js
  server/server.js
Labels: User story

#11 Few bug fixes related to Update Profile functionality
  client/public/images/avatar.png
  client/src/components/ProfileApp.js
  client/src/css/ProfileApp.css
  server/controllers/emailController.js
  server/controllers/userController.js
Labels: bug

#12 Few bug Fixes
  client/src/components/ProfileApp.js
Labels: bug

#14 Added code for pick job functionality and showing all jobs
  client/package-lock.json
  client/package.json
  client/public/images/homepage9.gif
  client/src/api/index.js
  client/src/components/AccountApp.js
  client/src/components/ForgotPasswordApp.js
  client/src/components/Notification.js
  client/src/components/PostJobApp.js
  client/src/components/ProfileApp.js
  client/src/components/RegisterApp.js
  client/src/css/AccountApp.css
  client/src/css/App.css
  client/src/css/Notification.css
  client/src/css/ProfileApp.css
  client/src/css/RegisterApp.css
  client/src/redux/actions/auth.js
  server/controllers/jobController.js
Labels: User story

#17 Added code for My Jobs Component
  client/src/api/index.js
  client/src/components/FetchJobApp.js
  client/src/css/FetchJobApp.css
  client/src/redux/actions/auth.js
  server/routes/jobRoutes.js
Labels: enhancement, Task
